version: "3"

services:
  nginx_server:
    image: nginx
    network_mode: "host"
    container_name: nginx_container
    restart: always
    # ports:
    #   - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
